version: "3.8"
services:
  sandwalker_frontend:
    environment:
      - VIRTUALHOST=sandwalker.sbrk.org
    build: ../
    ports:
    - "10002:5000"
    volumes:
    - "./data:/data"
  sandwalker_backend:
    build: ../pocket/
    ports:
    - "8081:8081"
    - "26656:26656"
    volumes:
    - "./data:/home/app/.pocket/data"
  sandwalker_cron:
    build: ../cron/
    volumes:
    - "./data:/data"
